[application]

[web.app]

# HTML title tag content
title = "Novel Distributions"

# Optimize WASM bundle size
[web.wasm-opt]
# Enable wasm-opt optimization
level = 4  # Maximum optimization (0-4)

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = ["assets/dev-hotreload-fix.js"]
