use serde::{Deserialize, Serialize};

pub fn allowed_countries() -> Vec<&'static str> {
    let mut countries = vec![
        // Primary (keep these first)
        "US", "GB", "CA", "AU", // Secondary (will be sorted)
        "AF", "DZ", "AS", "AD", "AI", "AG", "AR", "AM", "AW", "AT", "AZ", "BS", "BH", "BB", "BY",
        "BE", "BZ", "BM", "BO", "BQ", "BA", "BV", "BR", "IO", "BN", "BG", "KH", "KY", "CL", "CN",
        "CX", "CC", "CO", "CK", "CR", "HR", "CU", "CY", "CZ", "DE", "DK", "DM", "DO", "EC", "EG",
        "SV", "EE", "FK", "FO", "FJ", "FI", "FR", "GF", "PF", "TF", "GI", "GR", "GL", "GD", "GP",
        "GT", "GG", "GY", "HT", "HM", "VA", "HN", "HK", "HU", "IS", "ID", "IR", "IQ", "IE", "IM",
        "IT", "JM", "JP", "JE", "JO", "KZ", "KI", "KR", "KW", "KG", "LA", "LV", "LB", "LY", "LI",
        "LT", "LU", "MO", "MK", "MY", "MV", "MT", "MH", "MQ", "MX", "FM", "MD", "MC", "MN", "ME",
        "MS", "MA", "NP", "NL", "NC", "NZ", "NI", "NU", "NF", "MP", "NO", "OM", "PK", "PW", "PS",
        "PA", "PG", "PY", "PE", "PH", "PN", "PL", "PT", "PR", "QA", "RE", "RO", "BL", "SH", "KN",
        "LC", "MF", "PM", "VC", "WS", "SM", "ST", "SA", "RS", "SG", "SX", "SK", "SI", "SB", "ZA",
        "GS", "ES", "LK", "SR", "SJ", "SE", "CH", "SY", "TW", "TJ", "TH", "TL", "TK", "TO", "TT",
        "TN", "TR", "TM", "TC", "TV", "UA", "AE", "UM", "UY", "UZ", "VU", "VE", "VN", "VG", "VI",
        "WF", "YE", "GE",
    ];

    // Sort everything after the first 4 elements
    countries[4..].sort();
    countries
}

pub fn country_display_name_from_iso(iso: &str) -> String {
    let display: &str = match iso.to_ascii_uppercase().as_str() {
        // Original translations
        "US" => "United States",
        "GB" => "United Kingdom",
        "CA" => "Canada",
        "DE" => "Germany",
        "FR" => "France",
        "IT" => "Italy",
        "ES" => "Spain",
        "AU" => "Australia",
        "NZ" => "New Zealand",
        "IE" => "Ireland",
        "NL" => "Netherlands",
        "SE" => "Sweden",
        "NO" => "Norway",
        "DK" => "Denmark",
        "FI" => "Finland",
        "JP" => "Japan",
        "CN" => "China",
        "SG" => "Singapore",
        "HK" => "Hong Kong",
        "MX" => "Mexico",
        "BR" => "Brazil",

        // New country translations
        "AF" => "Afghanistan",
        "AL" => "Albania",
        "DZ" => "Algeria",
        "AS" => "American Samoa",
        "AD" => "Andorra",
        "AO" => "Angola",
        "AI" => "Anguilla",
        "AQ" => "Antarctica",
        "AG" => "Antigua and Barbuda",
        "AR" => "Argentina",
        "AM" => "Armenia",
        "AW" => "Aruba",
        "AT" => "Austria",
        "AZ" => "Azerbaijan",
        "BS" => "Bahamas",
        "BH" => "Bahrain",
        "BD" => "Bangladesh",
        "BB" => "Barbados",
        "BY" => "Belarus",
        "BE" => "Belgium",
        "BZ" => "Belize",
        "BJ" => "Benin",
        "BM" => "Bermuda",
        "BO" => "Bolivia",
        "BQ" => "Bonaire, Sint Eustatius and Saba",
        "BA" => "Bosnia and Herzegovina",
        "BW" => "Botswana",
        "BV" => "Bouvet Island",
        "BR" => "Brazil",
        "IO" => "British Indian Ocean Territory",
        "BN" => "Brunei Darussalam",
        "BG" => "Bulgaria",
        "BF" => "Burkina Faso",
        "BI" => "Burundi",
        "KH" => "Cambodia",
        "CM" => "Cameroon",
        "CV" => "Cape Verde",
        "KY" => "Cayman Islands",
        "CF" => "Central African Republic",
        "TD" => "Chad",
        "CL" => "Chile",
        "CX" => "Christmas Island",
        "CC" => "Cocos (Keeling) Islands",
        "CO" => "Colombia",
        "KM" => "Comoros",
        "CG" => "Congo",
        "CD" => "Congo, the Democratic Republic of the",
        "CK" => "Cook Islands",
        "CR" => "Costa Rica",
        "CI" => "Cote D'Ivoire",
        "HR" => "Croatia",
        "CU" => "Cuba",
        "CW" => "Curaçao",
        "CY" => "Cyprus",
        "CZ" => "Czech Republic",
        "DJ" => "Djibouti",
        "DM" => "Dominica",
        "DO" => "Dominican Republic",
        "EC" => "Ecuador",
        "EG" => "Egypt",
        "SV" => "El Salvador",
        "GQ" => "Equatorial Guinea",
        "ER" => "Eritrea",
        "EE" => "Estonia",
        "ET" => "Ethiopia",
        "FK" => "Falkland Islands (Malvinas)",
        "FO" => "Faroe Islands",
        "FJ" => "Fiji",
        "GF" => "French Guiana",
        "PF" => "French Polynesia",
        "TF" => "French Southern Territories",
        "GA" => "Gabon",
        "GM" => "Gambia",
        "GE" => "Georgia",
        "GH" => "Ghana",
        "GI" => "Gibraltar",
        "GR" => "Greece",
        "GL" => "Greenland",
        "GD" => "Grenada",
        "GP" => "Guadeloupe",
        "GU" => "Guam",
        "GT" => "Guatemala",
        "GG" => "Guernsey",
        "GN" => "Guinea",
        "GW" => "Guinea-Bissau",
        "GY" => "Guyana",
        "HT" => "Haiti",
        "HM" => "Heard Island And Mcdonald Islands",
        "VA" => "Holy See (Vatican City State)",
        "HN" => "Honduras",
        "HU" => "Hungary",
        "IS" => "Iceland",
        "IN" => "India",
        "ID" => "Indonesia",
        "IR" => "Iran, Islamic Republic of",
        "IQ" => "Iraq",
        "IM" => "Isle Of Man",
        "IL" => "Israel",
        "JM" => "Jamaica",
        "JE" => "Jersey",
        "JO" => "Jordan",
        "KZ" => "Kazakhstan",
        "KE" => "Kenya",
        "KI" => "Kiribati",
        "KP" => "Korea, Democratic People's Republic of",
        "KR" => "Korea, Republic of",
        "KW" => "Kuwait",
        "KG" => "Kyrgyzstan",
        "LA" => "Lao People's Democratic Republic",
        "LV" => "Latvia",
        "LB" => "Lebanon",
        "LS" => "Lesotho",
        "LR" => "Liberia",
        "LY" => "Libyan Arab Jamahiriya",
        "LI" => "Liechtenstein",
        "LT" => "Lithuania",
        "LU" => "Luxembourg",
        "MO" => "Macao",
        "MK" => "Macedonia, the Former Yugoslav Republic of",
        "MG" => "Madagascar",
        "MW" => "Malawi",
        "MY" => "Malaysia",
        "MV" => "Maldives",
        "ML" => "Mali",
        "MT" => "Malta",
        "MH" => "Marshall Islands",
        "MQ" => "Martinique",
        "MR" => "Mauritania",
        "MU" => "Mauritius",
        "YT" => "Mayotte",
        "FM" => "Micronesia, Federated States of",
        "MD" => "Moldova, Republic of",
        "MC" => "Monaco",
        "MN" => "Mongolia",
        "ME" => "Montenegro",
        "MS" => "Montserrat",
        "MA" => "Morocco",
        "MZ" => "Mozambique",
        "MM" => "Myanmar",
        "NA" => "Namibia",
        "NR" => "Nauru",
        "NP" => "Nepal",
        "NC" => "New Caledonia",
        "NI" => "Nicaragua",
        "NE" => "Niger",
        "NG" => "Nigeria",
        "NU" => "Niue",
        "NF" => "Norfolk Island",
        "MP" => "Northern Mariana Islands",
        "OM" => "Oman",
        "PK" => "Pakistan",
        "PW" => "Palau",
        "PS" => "Palestinian Territory, Occupied",
        "PA" => "Panama",
        "PG" => "Papua New Guinea",
        "PY" => "Paraguay",
        "PE" => "Peru",
        "PN" => "Pitcairn",
        "PL" => "Poland",
        "PR" => "Puerto Rico",
        "QA" => "Qatar",
        "RE" => "Reunion",
        "RO" => "Romania",
        "RU" => "Russian Federation",
        "RW" => "Rwanda",
        "BL" => "Saint Barthélemy",
        "SH" => "Saint Helena",
        "KN" => "Saint Kitts and Nevis",
        "LC" => "Saint Lucia",
        "MF" => "Saint Martin (French part)",
        "PM" => "Saint Pierre and Miquelon",
        "VC" => "Saint Vincent and the Grenadines",
        "WS" => "Samoa",
        "SM" => "San Marino",
        "ST" => "Sao Tome and Principe",
        "SA" => "Saudi Arabia",
        "SN" => "Senegal",
        "RS" => "Serbia",
        "SC" => "Seychelles",
        "SL" => "Sierra Leone",
        "SX" => "Sint Maarten",
        "SK" => "Slovakia",
        "SI" => "Slovenia",
        "SB" => "Solomon Islands",
        "SO" => "Somalia",
        "GS" => "South Georgia and the South Sandwich Islands",
        "SS" => "South Sudan",
        "LK" => "Sri Lanka",
        "SD" => "Sudan",
        "SR" => "Suriname",
        "SJ" => "Svalbard and Jan Mayen",
        "SZ" => "Swaziland",
        "SY" => "Syrian Arab Republic",
        "TW" => "Taiwan, Province of China",
        "TJ" => "Tajikistan",
        "TZ" => "Tanzania, United Republic of",
        "TH" => "Thailand",
        "TL" => "Timor Leste",
        "TG" => "Togo",
        "TK" => "Tokelau",
        "TO" => "Tonga",
        "TT" => "Trinidad and Tobago",
        "TN" => "Tunisia",
        "TR" => "Turkey",
        "TM" => "Turkmenistan",
        "TC" => "Turks and Caicos Islands",
        "TV" => "Tuvalu",
        "UG" => "Uganda",
        "UA" => "Ukraine",
        "AE" => "United Arab Emirates",
        "UM" => "United States Minor Outlying Islands",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistan",
        "VU" => "Vanuatu",
        "VE" => "Venezuela",
        "VN" => "Viet Nam",
        "VG" => "Virgin Islands, British",
        "VI" => "Virgin Islands, U.S.",
        "WF" => "Wallis and Futuna",
        "EH" => "Western Sahara",
        "YE" => "Yemen",
        "ZM" => "Zambia",
        "ZW" => "Zimbabwe",
        "XK" => "Kosovo",
        _ => iso, // Default to ISO code if not found
    };
    display.to_string()
}

pub fn available_countries_display() -> Vec<(String, String)> {
    allowed_countries()
        .into_iter()
        .map(|iso| (iso.to_string(), country_display_name_from_iso(iso)))
        .collect()
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LanguageOption {
    pub code: &'static str,
    pub flag: &'static str,
    pub name: &'static str,
    pub country: &'static str,
}

pub const LANGUAGE_OPTIONS: &[LanguageOption] = &[
    LanguageOption {
        code: "en-US",
        flag: "🇺🇸",
        name: "English",
        country: "United States",
    },
    LanguageOption {
        code: "de",
        flag: "🇩🇪",
        name: "Deutsch",
        country: "Deutschland",
    },
    LanguageOption {
        code: "it",
        flag: "🇮🇹",
        name: "Italiano",
        country: "Italia",
    },
    LanguageOption {
        code: "fr",
        flag: "🇫🇷",
        name: "Français",
        country: "France",
    },
    LanguageOption {
        code: "es",
        flag: "🇪🇸",
        name: "Español",
        country: "España",
    },
    LanguageOption {
        code: "pl-PL",
        flag: "🇵🇱",
        name: "Polski",
        country: "Polska",
    },
    LanguageOption {
        code: "el",
        flag: "🇬🇷",
        name: "Ελληνικά",
        country: "Ελλάδα",
    },
    LanguageOption {
        code: "bg",
        flag: "🇧🇬",
        name: "Български",
        country: "България",
    },
    LanguageOption {
        code: "hu",
        flag: "🇭🇺",
        name: "Magyar",
        country: "Magyarország",
    },
    LanguageOption {
        code: "cs",
        flag: "🇨🇿",
        name: "Čeština",
        country: "Česká republika",
    },
    LanguageOption {
        code: "nl",
        flag: "🇳🇱",
        name: "Nederlands",
        country: "Nederland",
    },
    LanguageOption {
        code: "no",
        flag: "🇳🇴",
        name: "Norsk",
        country: "Norge",
    },
    LanguageOption {
        code: "sv",
        flag: "🇸🇪",
        name: "Svenska",
        country: "Sverige",
    },
    LanguageOption {
        code: "fi",
        flag: "🇫🇮",
        name: "Suomi",
        country: "Suomi",
    },
    LanguageOption {
        code: "sk",
        flag: "🇸🇰",
        name: "Slovenčina",
        country: "Slovensko",
    },
    LanguageOption {
        code: "pt",
        flag: "🇵🇹",
        name: "Português",
        country: "Portugal",
    },

    LanguageOption {
        code: "ja",
        flag: "🇯🇵",
        name: "日本語",
        country: "日本",
    },
    LanguageOption {
        code: "ko",
        flag: "🇰🇷",
        name: "한국어",
        country: "대한민국",
    },
    LanguageOption {
        code: "zh",
        flag: "🇨🇳",
        name: "中文",
        country: "中国",
    },
];

pub fn get_language_by_code(code: &str) -> Option<&'static LanguageOption> {
    LANGUAGE_OPTIONS.iter().find(|lang| lang.code == code)
}
