//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6
use super::sea_orm_active_enums::AddressType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Address")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "orderId", column_type = "Text")]
    pub order_id: String,
    #[sea_orm(column_name = "customerId", column_type = "Text", nullable)]
    pub customer_id: Option<String>,
    #[sea_orm(column_name = "firstName", column_type = "Text")]
    pub first_name: String,
    #[sea_orm(column_name = "lastName", column_type = "Text")]
    pub last_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub company: Option<String>,
    #[sea_orm(column_name = "addressLine1", column_type = "Text")]
    pub address_line_1: String,
    #[sea_orm(column_name = "addressLine2", column_type = "Text", nullable)]
    pub address_line_2: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub city: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub province: Option<String>,
    #[sea_orm(column_name = "postalCode", column_type = "Text")]
    pub postal_code: String,
    #[sea_orm(column_type = "Text")]
    pub country: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    pub r#type: AddressType,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::order::Entity",
        from = "Column::OrderId",
        to = "super::order::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Orders,
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
