//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::ActiveValue;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "affiliate_withdrawls")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "affiliateId", column_type = "Text")]
    pub affiliate_id: String,
    #[sea_orm(column_type = "Text")]
    pub crypto: String,
    #[sea_orm(column_name = "cryptoAddress", column_type = "Text")]
    pub crypto_address: String,
    #[sea_orm(column_name = "txId", column_type = "Text", nullable)]
    pub tx_id: Option<String>,
    pub completed: bool,
    pub cancelled: bool,
    #[sea_orm(column_name = "completedAt", nullable)]
    pub completed_at: Option<DateTime>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::affiliate_users::Entity",
        from = "Column::AffiliateId",
        to = "super::affiliate_users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AffiliateUser,
}

impl Related<super::affiliate_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AffiliateUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
