//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::ActiveValue;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "affiliate_users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub level: i32,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub country: String,
    pub enabled: bool,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::discounts::Entity")]
    Discounts,

    #[sea_orm(has_many = "super::affiliate_withdrawls::Entity")]
    AffiliateWithdrawls,
}

impl Related<super::discounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Discounts.def()
    }
}

impl Related<super::affiliate_withdrawls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AffiliateWithdrawls.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
