//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use super::sea_orm_active_enums::ActorType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "AuditLog")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "actorId", column_type = "Text", nullable)]
    pub actor_id: Option<String>,
    #[sea_orm(column_name = "actorType")]
    pub actor_type: ActorType,
    #[sea_orm(column_type = "Text")]
    pub action: String,
    #[sea_orm(column_name = "entityType", column_type = "Text")]
    pub entity_type: String,
    #[sea_orm(column_name = "entityId", column_type = "Text")]
    pub entity_id: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
