//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use super::sea_orm_active_enums::ShippingOption;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "customer_baskets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "customerId", column_type = "Text", nullable)]
    pub customer_id: Option<String>,

    #[sea_orm(column_name = "countryCode", column_type = "Text", nullable)]
    pub country_code: Option<String>,
    #[sea_orm(column_name = "discountCode", column_type = "Text", nullable)]
    pub discount_code: Option<String>,
    #[sea_orm(column_name = "shippingOption", nullable)]
    pub shipping_option: Option<ShippingOption>,
    #[sea_orm(column_name = "stockLocationId", column_type = "Text", nullable)]
    pub stock_location_id: Option<String>,

    // Payment-related
    #[sea_orm(column_name = "locked")]
    pub locked: bool,
    #[sea_orm(column_name = "paymentId", column_type = "Text", nullable)]
    pub payment_id: Option<String>,

    #[sea_orm(column_name = "paymentFailedAt", nullable)]
    pub payment_failed_at: Option<DateTime>,

    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::basket_items::Entity")]
    BasketItems,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::stock_locations::Entity",
        from = "Column::StockLocationId",
        to = "super::stock_locations::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    StockLocations,
}

impl Related<super::basket_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BasketItems.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::stock_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockLocations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
