//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use super::sea_orm_active_enums::DiscountType;
use sea_orm::ActiveValue;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "discounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub code: String,
    #[sea_orm(column_name = "affiliateId", column_type = "Text", nullable)]
    pub affiliate_id: Option<String>,
    pub active: bool,
    #[sea_orm(column_name = "discountType")]
    pub discount_type: DiscountType,
    #[sea_orm(column_name = "discountPercentage", column_type = "Double", nullable)]
    pub discount_percentage: Option<f64>,
    #[sea_orm(column_name = "discountAmount", column_type = "Double", nullable)]
    pub discount_amount: Option<f64>,
    #[sea_orm(column_name = "amountUsed", column_type = "Double", nullable)]
    pub amount_used: Option<f64>,
    #[sea_orm(column_name = "maximumUses", nullable)]
    pub maximum_uses: Option<i32>,
    #[sea_orm(column_name = "discountUsed")]
    pub discount_used: i32,
    #[sea_orm(column_name = "activeReduceQuantity")]
    pub active_reduce_quantity: i32,
    #[sea_orm(column_name = "validCountries", nullable)]
    pub valid_countries: Option<Vec<String>>,
    #[sea_orm(column_name = "validAfterXProducts", nullable)]
    pub valid_after_x_products: Option<i32>,
    #[sea_orm(column_name = "validAfterXTotal", column_type = "Double", nullable)]
    pub valid_after_x_total: Option<f64>,
    #[sea_orm(column_name = "autoApply")]
    pub auto_apply: bool,
    #[sea_orm(column_name = "expireAt")]
    pub expire_at: Option<DateTime>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

impl Model {
    pub fn get_valid_countries(&self) -> Vec<String> {
        self.valid_countries.clone().unwrap_or_default()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::affiliate_users::Entity",
        from = "Column::AffiliateId",
        to = "super::affiliate_users::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    AffiliateUser,
}

impl Related<super::affiliate_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AffiliateUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
