//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "OrderItem")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "orderId", column_type = "Text")]
    pub order_id: String,
    #[sea_orm(column_name = "productVariantId", column_type = "Text")]
    pub product_variant_id: String,
    pub quantity: i32,
    #[sea_orm(column_name = "priceUsd", column_type = "Double")]
    pub price_usd: f64,
    #[sea_orm(column_name = "productTitle", column_type = "Text")]
    pub product_title: String,
    #[sea_orm(column_name = "variantName", column_type = "Text")]
    pub variant_name: String,
    pub pre_order_on_purchase: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::order::Entity",
        from = "Column::OrderId",
        to = "super::order::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Order,
    #[sea_orm(
        belongs_to = "super::product_variants::Entity",
        from = "Column::ProductVariantId",
        to = "super::product_variants::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    ProductVariants,
    #[sea_orm(has_many = "super::pre_order::Entity")]
    PreOrder,
}

impl Related<super::order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Order.def()
    }
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
