//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use super::sea_orm_active_enums::PaymentStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "Payment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "orderId", column_type = "Text", nullable)]
    pub order_id: Option<String>, // changed to option
    #[sea_orm(column_type = "Text")]
    pub method: String,
    #[sea_orm(column_name = "processorRef", column_type = "Text", nullable)]
    pub processor_ref: Option<String>,
    #[sea_orm(column_name = "processorUrl", column_type = "Text", nullable)]
    pub processor_url: Option<String>,
    pub status: PaymentStatus,
    #[sea_orm(column_name = "amountUsd", column_type = "Double")]
    pub amount_usd: f64,
    #[sea_orm(column_name = "paidAt")]
    pub paid_at: Option<DateTime>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::order::Entity",
        from = "Column::OrderId",
        to = "super::order::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Order,
}

impl Related<super::order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Order.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
