//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use super::sea_orm_active_enums::ProductForm;
use super::sea_orm_active_enums::ProductPhase;
use super::sea_orm_active_enums::ProductVisibility;
use sea_orm::entity::prelude::*;
use sea_orm::ActiveValue;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub subtitle: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub handle: String,
    #[sea_orm(column_name = "collections", nullable)]
    pub collections: Option<Vec<String>>,
    #[sea_orm(column_name = "productForm")]
    pub product_form: ProductForm,
    #[sea_orm(column_name = "physicalDescription", column_type = "Text", nullable)]
    pub physical_description: Option<String>,
    #[sea_orm(column_name = "defaultVariantId", column_type = "Text", nullable)]
    pub default_variant_id: Option<String>,
    #[sea_orm(column_name = "forceNoStock")]
    pub force_no_stock: bool,
    #[sea_orm(column_name = "plabsNodeId", column_type = "Text", nullable)]
    pub plabs_node_id: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub purity: Option<f64>,
    pub visibility: ProductVisibility,
    #[sea_orm(column_name = "smallDescriptionMd", column_type = "Text", nullable)]
    pub small_description_md: Option<String>,
    #[sea_orm(column_name = "mainDescriptionMd", column_type = "Text", nullable)]
    pub main_description_md: Option<String>,
    #[sea_orm(column_name = "alternateNames", nullable)]
    pub alternate_names: Option<Vec<String>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cas: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub iupac: Option<String>,
    #[sea_orm(column_name = "molForm", column_type = "Text", nullable)]
    pub mol_form: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub smiles: Option<String>,
    #[sea_orm(column_name = "enableRenderIfSmiles")]
    pub enable_render_if_smiles: bool,
    #[sea_orm(column_name = "pubchemCid", column_type = "Text", nullable)]
    pub pubchem_cid: Option<String>,
    #[sea_orm(column_name = "calculatedAdmet", column_type = "Double", nullable)]
    pub calculated_admet: Option<f64>,
    #[sea_orm(column_name = "analysisUrlQnmr", column_type = "Text", nullable)]
    pub analysis_url_qnmr: Option<String>,
    #[sea_orm(column_name = "analysisUrlHplc", column_type = "Text", nullable)]
    pub analysis_url_hplc: Option<String>,
    #[sea_orm(column_name = "analysisUrlQh1", column_type = "Text", nullable)]
    pub analysis_url_qh1: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub weight: Option<f64>, // DEPRECATE
    #[sea_orm(column_name = "dimensionsHeight", column_type = "Double", nullable)]
    pub dimensions_height: Option<f64>,
    #[sea_orm(column_name = "dimensionsLength", column_type = "Double", nullable)]
    pub dimensions_length: Option<f64>,
    #[sea_orm(column_name = "dimensionsWidth", column_type = "Double", nullable)]
    pub dimensions_width: Option<f64>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "preOrder")]
    pub pre_order: bool, // default: false
    #[sea_orm(column_name = "preOrderGoal", column_type = "Double", nullable)]
    pub pre_order_goal: Option<f64>,
    #[sea_orm(nullable)]
    pub priority: Option<i32>,
    #[sea_orm(nullable)]
    pub brand: Option<String>,
    #[sea_orm(column_name = "phase")]
    pub phase: ProductPhase,
    #[sea_orm(column_type = "Text", nullable)]
    pub mechanism: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata: Option<String>,
    #[sea_orm(column_name = "backOrder")]
    pub back_order: bool, // default: false
    #[sea_orm(nullable)]
    pub access_groups: Option<Vec<String>>,
    #[sea_orm(column_name = "access_users", nullable)]
    pub access_users: Option<Vec<String>>,
    //#[sea_orm(column_name = "show_private_preview")]
    pub show_private_preview: bool, // default: false
}

// Remove the helper methods since we're now using Vec<String> directly
impl Model {
    // You can still add helper methods if needed, but they're simpler now
    pub fn get_alternate_names(&self) -> Vec<String> {
        self.alternate_names.clone().unwrap_or_default()
    }

    pub fn get_access_groups(&self) -> Vec<String> {
        self.access_groups.clone().unwrap_or_default()
    }

    pub fn get_access_users(&self) -> Vec<String> {
        self.access_users.clone().unwrap_or_default()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::product_images::Entity")]
    ProductImages,

    // Relationship to ALL variants of this product (this is what was missing!)
    #[sea_orm(has_many = "super::product_variants::Entity")]
    ProductVariants,

    // Relationship to the DEFAULT variant specifically
    #[sea_orm(
        belongs_to = "super::product_variants::Entity",
        from = "Column::DefaultVariantId",
        to = "super::product_variants::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    DefaultVariant,
}

impl Related<super::product_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductImages.def()
    }
}

// This will now find ALL variants for the product (not just the default one)
impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
