//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "product_variants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "variantName", column_type = "Text")]
    pub variant_name: String,
    #[sea_orm(column_name = "productId", column_type = "Text")]
    pub product_id: String,
    #[sea_orm(column_name = "pbxSku", column_type = "Text", nullable)]
    pub pbx_sku: Option<String>, // Like PBX0001
    #[sea_orm(column_name = "thumbnailUrl", column_type = "Text", nullable)]
    pub thumbnail_url: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub weight: Option<f64>,
    #[sea_orm(column_name = "priceStandardUsd", column_type = "Double")]
    pub price_standard_usd: f64,
    #[sea_orm(
        column_name = "priceStandardWithoutSale",
        column_type = "Double",
        nullable
    )]
    pub price_standard_without_sale: Option<f64>,
    #[sea_orm(column_name = "additionalThumbnailUrls", nullable)]
    pub additional_thumbnail_urls: Option<Vec<String>>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    OrderItem,
    BasketItems,
    Products,
    VariantImages,
    ProductVariantStockItemRelations,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::OrderItem => Entity::has_many(super::order_item::Entity).into(),
            Self::BasketItems => Entity::has_many(super::basket_items::Entity).into(),
            Self::Products => Entity::belongs_to(super::products::Entity)
                .from(Column::ProductId)
                .to(super::products::Column::Id)
                .into(),
            Self::VariantImages => Entity::has_many(super::variant_images::Entity).into(),
            Self::ProductVariantStockItemRelations => {
                Entity::has_many(super::product_variant_stock_item_relations::Entity).into()
            }
        }
    }
}

impl Related<super::order_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderItem.def()
    }
}

impl Related<super::basket_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BasketItems.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::variant_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VariantImages.def()
    }
}

impl Related<super::product_variant_stock_item_relations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariantStockItemRelations.def()
    }
}

// Many-to-many relationship through the junction table
impl Related<super::stock_items::Entity> for Entity {
    fn to() -> RelationDef {
        super::product_variant_stock_item_relations::Relation::StockItems.def()
    }

    fn via() -> Option<RelationDef> {
        Some(
            super::product_variant_stock_item_relations::Relation::ProductVariants
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
