//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ActorType")]
pub enum ActorType {
    #[sea_orm(string_value = "CUSTOMER")]
    Customer,
    #[sea_orm(string_value = "MANAGER")]
    Manager,
    #[sea_orm(string_value = "SYSTEM")]
    System,
}

impl std::fmt::Display for ActorType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ActorType::Customer => write!(f, "CUSTOMER"),
            ActorType::Manager => write!(f, "MANAGER"),
            ActorType::System => write!(f, "SYSTEM"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "AddressType")]
pub enum AddressType {
    #[sea_orm(string_value = "BILLING")]
    Billing,
    #[sea_orm(string_value = "SHIPPING")]
    Shipping,
}

impl std::fmt::Display for AddressType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AddressType::Billing => write!(f, "BILLING"),
            AddressType::Shipping => write!(f, "SHIPPING"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ManagerPermission")]
pub enum ManagerPermission {
    #[sea_orm(string_value = "ACCOUNTING")]
    Accounting,
    #[sea_orm(string_value = "ADMIN")]
    Admin,
    #[sea_orm(string_value = "FULFILLMENT")]
    Fulfillment,
    #[sea_orm(string_value = "INVENTORY")]
    Inventory,
    #[sea_orm(string_value = "MANAGER")]
    Manager,
}

impl std::fmt::Display for ManagerPermission {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ManagerPermission::Accounting => write!(f, "ACCOUNTING"),
            ManagerPermission::Admin => write!(f, "ADMIN"),
            ManagerPermission::Fulfillment => write!(f, "FULFILLMENT"),
            ManagerPermission::Inventory => write!(f, "INVENTORY"),
            ManagerPermission::Manager => write!(f, "MANAGER"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "OrderStatus")]
pub enum OrderStatus {
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
    #[sea_orm(string_value = "FULFILLED")]
    Fulfilled,
    #[sea_orm(string_value = "PAID")]
    Paid,
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "PROCESSING")]
    // Is this needed?
    Processing,
    #[sea_orm(string_value = "REFUNDED")]
    Refunded,
}

impl std::fmt::Display for OrderStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            OrderStatus::Cancelled => write!(f, "CANCELLED"),
            OrderStatus::Fulfilled => write!(f, "FULFILLED"),
            OrderStatus::Paid => write!(f, "PAID"),
            OrderStatus::Pending => write!(f, "PENDING"),
            OrderStatus::Processing => write!(f, "PROCESSING"),
            OrderStatus::Refunded => write!(f, "REFUNDED"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "PaymentStatus")]
pub enum PaymentStatus {
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
    #[sea_orm(string_value = "FAILED")]
    Failed,
    #[sea_orm(string_value = "PAID")]
    Paid,
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "REFUNDED")]
    Refunded,
    #[sea_orm(string_value = "EXPIRED")]
    Expired,
}

impl std::fmt::Display for PaymentStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PaymentStatus::Cancelled => write!(f, "CANCELLED"),
            PaymentStatus::Failed => write!(f, "FAILED"),
            PaymentStatus::Paid => write!(f, "PAID"),
            PaymentStatus::Pending => write!(f, "PENDING"),
            PaymentStatus::Refunded => write!(f, "REFUNDED"),
            PaymentStatus::Expired => write!(f, "EXPIRED"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ProductForm")]
pub enum ProductForm {
    #[sea_orm(string_value = "AMPOULE")]
    Ampoule,
    #[sea_orm(string_value = "CAPSULES")]
    Capsules,
    #[sea_orm(string_value = "CONTAINER")]
    Container,
    #[sea_orm(string_value = "DIRECT_SPRAY")]
    DirectSpray,
    #[sea_orm(string_value = "MULTI")]
    Multi,
    #[sea_orm(string_value = "OTHER")]
    Other,
    #[sea_orm(string_value = "SOLUTION")]
    Solution,
    #[sea_orm(string_value = "VERTICAL_SPRAY")]
    VerticalSpray,
    #[sea_orm(string_value = "VIAL")]
    Vial,
}

impl std::fmt::Display for ProductForm {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProductForm::Ampoule => write!(f, "AMPOULE"),
            ProductForm::Capsules => write!(f, "CAPSULES"),
            ProductForm::Container => write!(f, "CONTAINER"),
            ProductForm::DirectSpray => write!(f, "DIRECT_SPRAY"),
            ProductForm::Multi => write!(f, "MULTI"),
            ProductForm::Other => write!(f, "OTHER"),
            ProductForm::Solution => write!(f, "SOLUTION"),
            ProductForm::VerticalSpray => write!(f, "VERTICAL_SPRAY"),
            ProductForm::Vial => write!(f, "VIAL"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ProductVisibility")]
pub enum ProductVisibility {
    #[sea_orm(string_value = "PRIVATE")]
    Private,
    #[sea_orm(string_value = "PUBLIC")]
    Public,
    #[sea_orm(string_value = "UNLISTED")]
    Unlisted,
}

impl std::fmt::Display for ProductVisibility {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProductVisibility::Private => write!(f, "PRIVATE"),
            ProductVisibility::Public => write!(f, "PUBLIC"),
            ProductVisibility::Unlisted => write!(f, "UNLISTED"),
        }
    }
}

/*
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "quantity_type")]
pub enum QuantityType {
    #[sea_orm(string_value = "GRAMS")]
    Grams,
    #[sea_orm(string_value = "LITERS")]
    Liters,
    #[sea_orm(string_value = "MILLIGRAMS")]
    Milligrams,
    #[sea_orm(string_value = "MILLILITERS")]
    Milliliters,
    #[sea_orm(string_value = "UNITS")]
    Units,
}

impl std::fmt::Display for QuantityType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            QuantityType::Grams => write!(f, "GRAMS"),
            QuantityType::Liters => write!(f, "LITERS"),
            QuantityType::Milligrams => write!(f, "MILLIGRAMS"),
            QuantityType::Milliliters => write!(f, "MILLILITERS"),
            QuantityType::Units => write!(f, "UNITS"),
        }
    }
}
*/

// NEW INVENTORY ENUMS

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "stock_unit")]
pub enum StockUnit {
    #[sea_orm(string_value = "MULTIPLES")]
    Multiples,
    #[sea_orm(string_value = "GRAMS")]
    Grams,
    #[sea_orm(string_value = "MILLILITERS")]
    Milliliters,
}

impl std::fmt::Display for StockUnit {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            StockUnit::Multiples => write!(f, "Multiples"),
            StockUnit::Grams => write!(f, "Grams"),
            StockUnit::Milliliters => write!(f, "Milliliters"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "stock_mode")]
pub enum StockMode {
    #[sea_orm(string_value = "CALCULATED")]
    Calculated,
    #[sea_orm(string_value = "FORCE_STOCKED")]
    ForceStocked,
    #[sea_orm(string_value = "FORCE_UNSTOCKED")]
    ForceUnstocked,
}

impl std::fmt::Display for StockMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            StockMode::Calculated => write!(f, "Calculated"),
            StockMode::ForceStocked => write!(f, "Force Stocked"),
            StockMode::ForceUnstocked => write!(f, "Force Unstocked"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "stock_batch_status")]
pub enum StockBatchStatus {
    #[sea_orm(string_value = "DRAFT")]
    Draft,
    #[sea_orm(string_value = "PAID")]
    Paid,
    #[sea_orm(string_value = "COMPLETE")]
    Complete,
    #[sea_orm(string_value = "ISSUE")]
    Issue,
}

impl std::fmt::Display for StockBatchStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            StockBatchStatus::Draft => write!(f, "Draft"),
            StockBatchStatus::Paid => write!(f, "Paid"),
            StockBatchStatus::Complete => write!(f, "Complete"),
            StockBatchStatus::Issue => write!(f, "Issue"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "stock_batch_location"
)]
pub enum StockBatchLocation {
    #[sea_orm(string_value = "EU")]
    EU,
}

impl std::fmt::Display for StockBatchLocation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            StockBatchLocation::EU => write!(f, "EU"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "shipping_option")]
pub enum ShippingOption {
    #[sea_orm(string_value = "TRACKED")]
    Tracked,
    #[sea_orm(string_value = "EXPRESS")]
    Express,
    #[sea_orm(string_value = "TRACKED_US")]
    TrackedUS,
}

impl std::fmt::Display for ShippingOption {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ShippingOption::Tracked => write!(f, "Tracked"),
            ShippingOption::Express => write!(f, "Express"),
            ShippingOption::TrackedUS => write!(f, "Tracked US"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "discount_type")]
pub enum DiscountType {
    #[sea_orm(string_value = "PERCENTAGE")]
    Percentage,
    #[sea_orm(string_value = "FIXED_AMOUNT")]
    FixedAmount,
    #[sea_orm(string_value = "PERCENTAGE_ON_SHIPPING")]
    PercentageOnShipping,
    #[sea_orm(string_value = "FIXED_AMOUNT_ON_SHIPPING")]
    FixedAmountOnShipping,
}

impl std::fmt::Display for DiscountType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DiscountType::Percentage => write!(f, "Percentage"),
            DiscountType::FixedAmount => write!(f, "Fixed Amount"),
            DiscountType::PercentageOnShipping => write!(f, "Percentage on shipping"),
            DiscountType::FixedAmountOnShipping => write!(f, "Fixed amount on shipping"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "product_phase")]
pub enum ProductPhase {
    #[sea_orm(string_value = "BLUE")]
    Blue,
    #[sea_orm(string_value = "PURPLE")]
    Purple,
    #[sea_orm(string_value = "ORANGE")]
    Orange,
}

impl std::fmt::Display for ProductPhase {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProductPhase::Blue => write!(f, "Blue"),
            ProductPhase::Purple => write!(f, "Purple"),
            ProductPhase::Orange => write!(f, "Orange"),
        }
    }
}
