//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use super::sea_orm_active_enums::QuantityType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "stock_dependencies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "parentStockItemId", column_type = "Text")]
    pub parent_stock_item_id: String,
    #[sea_orm(column_name = "childStockItemId", column_type = "Text")]
    pub child_stock_item_id: String,
    #[sea_orm(column_name = "requiredQuantity", column_type = "Double")]
    pub required_quantity: f64,
    #[sea_orm(column_name = "quantityType")]
    pub quantity_type: QuantityType,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::stock_items::Entity",
        from = "Column::ChildStockItemId",
        to = "super::stock_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    StockItems2,
    #[sea_orm(
        belongs_to = "super::stock_items::Entity",
        from = "Column::ParentStockItemId",
        to = "super::stock_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    StockItems1,
}

impl ActiveModelBehavior for ActiveModel {}
