//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use super::sea_orm_active_enums::QuantityType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "stock_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_name = "variantId", column_type = "Text", nullable)]
    pub variant_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sku: Option<String>, // e.g PBI0001
    #[sea_orm(column_name = "imageUrlPath", column_type = "Text", nullable)]
    pub image_url_path: Option<String>,
    #[sea_orm(column_name = "isScoop")]
    pub is_scoop: bool,
    #[sea_orm(column_name = "inStockQuantity", column_type = "Double")]
    pub in_stock_quantity: f64,
    #[sea_orm(column_name = "unitOfMeasure")]
    pub unit_of_measure: QuantityType,
    #[sea_orm(column_name = "minStockLevel", column_type = "Double", nullable)]
    pub min_stock_level: Option<f64>,
    #[sea_orm(
        column_name = "estimatedCostPerBatch",
        column_type = "Double",
        nullable
    )]
    pub estimated_cost_per_batch: Option<f64>,
    #[sea_orm(column_name = "batchQuantity", column_type = "Double", nullable)]
    pub batch_quantity: Option<f64>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_variants::Entity",
        from = "Column::VariantId",
        to = "super::product_variants::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    ProductVariants,
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
